function FOM_data_consistency_check(options_ROM,options_FOM)

if ~(isequal(options_ROM.case,options_FOM.case) && ...
        isequal(options_ROM.fluid,options_FOM.fluid) && ...
        isequal(options_ROM.visc,options_FOM.visc) && ...
        isequal(options_ROM.grid,options_FOM.grid) && ...
        isequal(options_ROM.discretization,options_FOM.discretization) && ...
        isequal(options_ROM.force,options_FOM.force) && ...
        isequal(options_ROM.ibm,options_FOM.ibm) && ...
        isequal(options_ROM.BC,options_FOM.BC) )
    warning('FOM options and ROM options are not consistent')
end


        

